[package]
name = "uuid-utils"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "uuid"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }

[dependencies.uuid]
version = "1.19.0"
features = ["v4", "v7"]
